version: "3.7"
services:
  db:
    image: mysql:${DB_IMAGE_TAG}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - backend
    volumes:
      - ${DB_DATA}:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    image: kinnaradigitalstudio/kecak-workflow:${WFLOW_IMAGE_TAG}
    depends_on:
      - "db"
    environment:
      - JAVA_OPTS=${WFLOW_JAVA_OPTS}
      - TOMCAT_DEBUG=${TOMCAT_DEBUG}
    #links:
    #  # database is accessible from web by using hostname 'db'
    #  - "db:db"
    networks:
      - backend
    volumes:
      - ${WFLOW_DIR}:/usr/local/tomcat/wflow
      - ${WFLOW_LOGS}:/usr/local/tomcat/logs
    ports:
      # application port
      - "8080:8080"

      # debugging port
      - "8000:${TOMCAT_DEBUG_PORT}"

    command : ["wait-for-it", "db:3306", "--", "/usr/local/tomcat/tomcat.sh", "run"]
  proxy:
    image: kinnaradigitalstudio/kecak-proxy:${PROXY_IMAGE_TAG}
    depends_on:
      - "web"
      - "db"
    #links:
    #  - "web:web"
    networks:
      - backend
    ports:
      - "80:80"
    environment:
      - PROXY_HOST
      - PROXY_DEFAULT_PORT
      - PROXY_MAX_UPLOAD_SIZE
    command : ["wait-for-it", "web:8080", "--", "/usr/local/bin/start.sh"]
networks:
  backend:
volumes:
  db_data:
  wflow_dir:
  wflow_logs:
  proxy_dir:
  
